services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - windswept-net

  migrate:
    image: jakemackie/windswept:latest
    platform: linux/amd64
    command: npx prisma migrate deploy
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    networks:
      - windswept-net
    restart: "no"

  generate:
    image: jakemackie/windswept:latest
    platform: linux/amd64
    command: npx prisma generate
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - migrate
    networks:
      - windswept-net
    restart: "no"

  client:
    image: jakemackie/windswept:latest
    platform: linux/amd64
    command: node dist/index.js
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
    restart: unless-stopped
    depends_on:
      - generate
    networks:
      - windswept-net

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - windswept-net

volumes:
  pgdata_prod:

networks:
  windswept-net:
    driver: bridge
