services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - windswept-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  migrate:
    build:
      context: .
    image: jakemackie/windswept:latest
    platform: linux/amd64
    command: npx prisma migrate deploy
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      backup:
        condition: service_completed_successfully
    networks:
      - windswept-net
    restart: "no"

  backup:
    build:
      context: .
    image: jakemackie/windswept:latest
    platform: linux/amd64
    command: |
      sh -c "
        echo 'Creating backup before migration...'
        pg_dump -h db -U $${POSTGRES_USER} -d $${POSTGRES_DB} > /tmp/backup_$$(date +%Y%m%d_%H%M%S).sql
        echo 'Backup completed'
      "
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - windswept-net
    restart: "no"
    volumes:
      - ./backups:/tmp

  generate:
    build:
      context: .
    image: jakemackie/windswept:latest
    platform: linux/amd64
    command: npx prisma generate
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - windswept-net
    restart: "no"

  client:
    build:
      context: .
    image: jakemackie/windswept:latest
    platform: linux/amd64
    command: node dist/index.js
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
    restart: unless-stopped
    depends_on:
      generate:
        condition: service_completed_successfully
    networks:
      - windswept-net

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - windswept-net

volumes:
  pgdata_prod:

networks:
  windswept-net:
    driver: bridge
