services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: windswept
      POSTGRES_PASSWORD: windswept
      POSTGRES_DB: windswept
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - windswept-net

  client:
    build:
      context: .
    image: jakemackie/windswept:dev
    command: node dist/index.js
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
    restart: unless-stopped
    volumes:
      - ./dist:/app/dist
    depends_on:
      db:
        condition: service_healthy
    networks:
      - windswept-net

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - windswept-net

volumes:
  pgdata_dev:

networks:
  windswept-net:
    driver: bridge