services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: windswept
      POSTGRES_PASSWORD: windswept
      POSTGRES_DB: windswept
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - windswept-net

volumes:
  pgdata_dev:

networks:
  windswept-net:
    driver: bridge
