services:
  # Service for local development with Doppler (default)
  client:
    build:
      context: .
    image: windswept
    command: node dist/index.js
    environment:
      - DISCORD_TOKEN
    restart: unless-stopped
    profiles:
      - local
    volumes:
      - ./dist:/app/dist
      - ./node_modules:/app/node_modules

  # Service for CI/CD with .env file
  client-ci:
    build:
      context: .
    image: windswept
    command: node dist/index.js
    environment:
      - DISCORD_TOKEN
    env_file:
      - .env
    restart: unless-stopped
    profiles:
      - ci
