import { PermissionFlagsBits } from 'discord.js';

export const permissionLabels: Partial<Record<keyof typeof PermissionFlagsBits, string>> = {
  CreateInstantInvite: 'Create Invite',
  KickMembers: 'Kick Members',
  BanMembers: 'Ban Members',
  Administrator: 'Administrator',
  ManageChannels: 'Manage Channels',
  ManageGuild: 'Manage Server',
  AddReactions: 'Add Reactions',
  ViewAuditLog: 'View Audit Log',
  PrioritySpeaker: 'Priority Speaker',
  Stream: 'Video',
  ViewChannel: 'View Channels',
  SendMessages: 'Send Messages',
  SendTTSMessages: 'Send TTS Messages',
  ManageMessages: 'Manage Messages',
  EmbedLinks: 'Embed Links',
  AttachFiles: 'Attach Files',
  ReadMessageHistory: 'Read Message History',
  MentionEveryone: 'Mention Everyone',
  UseExternalEmojis: 'Use External Emojis',
  ViewGuildInsights: 'View Server Insights',
  Connect: 'Connect to Voice',
  Speak: 'Speak in Voice',
  MuteMembers: 'Mute Members',
  DeafenMembers: 'Deafen Members',
  MoveMembers: 'Move Members',
  UseVAD: 'Use Voice Activity',
  ChangeNickname: 'Change Nickname',
  ManageNicknames: 'Manage Nicknames',
  ManageRoles: 'Manage Roles',
  ManageWebhooks: 'Manage Webhooks',
  ManageEmojisAndStickers: 'Manage Emojis/Stickers',
  ManageGuildExpressions: 'Manage Expressions',
  UseApplicationCommands: 'Use Slash Commands',
  RequestToSpeak: 'Request to Speak',
  ManageEvents: 'Manage Events',
  ManageThreads: 'Manage Threads',
  CreatePublicThreads: 'Create Public Threads',
  CreatePrivateThreads: 'Create Private Threads',
  UseExternalStickers: 'Use External Stickers',
  SendMessagesInThreads: 'Send Messages in Threads',
  UseEmbeddedActivities: 'Start Activities',
  ModerateMembers: 'Timeout Members',
  ViewCreatorMonetizationAnalytics: 'View Monetization Analytics',
  UseSoundboard: 'Use Soundboard',
  CreateGuildExpressions: 'Create Expressions',
  CreateEvents: 'Create Events',
  UseExternalSounds: 'Use External Sounds',
  SendVoiceMessages: 'Send Voice Messages',
  SendPolls: 'Send Polls',
  UseExternalApps: 'Use External Apps',
};
