name: Production Deployment

on:
  push:
    branches:
      - deployment/production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Connect
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

          cat > .env <<EOF
          DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          DATABASE_URL=postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/${{ secrets.POSTGRES_DB }}?schema=public
          EOF

      - name: Sync
        run: |
          rsync -avz \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='dist' \
            -e "ssh -i ~/.ssh/id_rsa" \
            ./ root@${{ secrets.SSH_HOST }}:/home/windswept/

      - name: Restart
        run: |
          ssh -i ~/.ssh/id_rsa root@${{ secrets.SSH_HOST }} <<'EOF'
          sudo systemctl restart windswept.service
          EOF
